name: Reusable Publish Docker

on:
  workflow_call:
    inputs:
      runner:
        description: "Runner to use for the workflow"
        type: string
        default: "zondax-runners"
      timeout_minutes:
        description: "Timeout in minutes for the job"
        type: number
        default: 15
      checkout_ref:
        description: "The ref to checkout (branch, tag, SHA)"
        type: string
        default: ""
        required: false
    secrets:
      DOCKERHUB_USER:
        description: "Docker Hub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub access token"
        required: true

jobs:
  publish:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
      packages: write
      id-token: write  # Needed for SLSA provenance
    steps:
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -yy git make

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout_ref || github.event.pull_request.head.ref || github.ref }}

      - name: Debug GitHub variables
        run: |
          echo "Debug GitHub variables:"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
          echo "github.sha: ${{ github.sha }}"

      - name: Set branch name
        run: |
          echo "Setting branch name..."
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            GIT_BRANCH_GITHUB="${{ github.head_ref }}"
            echo "Using PR head ref: $GIT_BRANCH_GITHUB"
          else
            GIT_BRANCH_GITHUB="${{ github.ref_name }}"
            echo "Using ref name: $GIT_BRANCH_GITHUB"
          fi
          echo "GIT_BRANCH_GITHUB=$GIT_BRANCH_GITHUB" >> $GITHUB_ENV
          echo "GIT_BRANCH_GITHUB=$GIT_BRANCH_GITHUB"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.15.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Info before publishing
        run: |
          make docker-info

      - name: Publish
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
        run: |
          make docker-publish
