name: Publish zup make
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v[0-9]+"
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: ["*"]
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-images:
    name: Publish Docker Image
    uses: ./.github/workflows/publish-docker.yaml
    with:
      checkout_ref: ${{ github.event.pull_request.head.ref || github.ref }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
