name: Reusable Infra Checks

on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use for the workflow"
        type: "string"
        default: "zondax-runners"
        required: false
      container_image:
        description: "The container image to use"
        type: "string"
        default: "oven/bun:1-alpine"
        required: false
      kubeconform_version:
        description: "The version of kubeconform to use"
        type: "string"
        default: "v0.6.7"
        required: false
      make_command:
        description: "The make command to run for infra checks"
        type: "string"
        default: "infra-checks"
        required: false
      github_app_auth:
        description: "Use GitHub App Token"
        required: false
        type: boolean
        default: false
      github_app_repos:
        description: "Additional repositories to access (one per line)"
        required: false
        type: string
        default: ""
      timeout_minutes:
        description: "Timeout in minutes for the job"
        type: number
        default: 10
    secrets:
      app_id:
        description: "GitHub App ID"
        required: false
      app_pem:
        description: "GitHub App PEM"
        required: false

jobs:
  infra-checks:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.container_image }}
    timeout-minutes: ${{ inputs.timeout_minutes }}

    steps:
      - name: Checkout with GitHub App
        uses: zondax/_actions/checkout-with-app@main
        with:
          github_app_auth: ${{ inputs.github_app_auth }}
          github_app_repos: ${{ inputs.github_app_repos }}
          app_id: ${{ secrets.app_id }}
          app_pem: ${{ secrets.app_pem }}

      - name: Install dependencies
        run: |
          apk add --no-cache make wget tar

      - name: Install kubeconform
        env:
          KUBECONFORM_VERSION: ${{ inputs.kubeconform_version }}
          KUBECONFORM_ARCH: linux-amd64
          KUBECONFORM_URL: https://github.com/yannh/kubeconform/releases/download
        run: |
          wget ${KUBECONFORM_URL}/${KUBECONFORM_VERSION}/kubeconform-${KUBECONFORM_ARCH}.tar.gz
          tar xzf kubeconform-${KUBECONFORM_ARCH}.tar.gz
          mv kubeconform /usr/local/bin/

      - name: Validate Infra manifests
        run: |
          bun install
          make ${{ inputs.make_command }}
