name: Reusable Infra Checks

on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use for the workflow"
        type: "string"
        default: "zondax-runners"
        required: false
      container_image:
        description: "The container image to use"
        type: "string"
        default: "oven/bun:1-alpine"
        required: false
      kubeconform_version:
        description: "The version of kubeconform to use"
        type: "string"
        default: "v0.6.7"
        required: false
      make_command:
        description: "The make command to run for infra checks"
        type: "string"
        default: "infra-checks"
        required: false
      app_id:
        description: "GitHub App ID"
        required: false
        type: string
        default: ""
      app_pem:
        description: "GitHub App PEM"
        required: false
        type: string
        default: ""
      repositories:
        description: "Additional repositories to access (one per line)"
        required: false
        type: string
        default: ""

jobs:
  infra-checks:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.container_image }}
    timeout-minutes: 15

    env:
      GITHUB_APP_ID: ${{ inputs.app_id }}
      GITHUB_APP_PEM: ${{ inputs.app_pem }}

    steps:
      - name: Generate GitHub App Token
        id: app-token
        if: ${{ inputs.app_id != '' && inputs.app_pem != '' }}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_APP_PEM }}
          repositories: |
            ${{ github.event.repository.full_name }}
            ${{ inputs.repositories }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token || github.token }}

      - name: Install kubeconform
        env:
          KUBECONFORM_VERSION: ${{ inputs.kubeconform_version }}
          KUBECONFORM_ARCH: linux-amd64
          KUBECONFORM_URL: https://github.com/yannh/kubeconform/releases/download
        run: |
          make infra-kubeconform-install

      - name: Validate Infra manifests
        run: |
          bun install
          make ${{ inputs.make_command }}
