name: Reusable YAML Checks

on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use for the workflow"
        type: "string"
        default: "zondax-runners"
        required: false
      container_image:
        description: "The container image to use"
        type: "string"
        default: "oven/bun:1-alpine"
        required: false
      make_command:
        description: "The make command to run for yaml checks"
        type: "string"
        default: "yaml-checks"
        required: false
      github_app_auth:
        description: "Use GitHub App Token"
        required: false
        type: boolean
        default: false
      github_app_repos:
        description: "Additional repositories to access (one per line)"
        required: false
        type: string
        default: ""
    secrets:
      app_id:
        description: "GitHub App ID"
        required: false
      app_pem:
        description: "GitHub App PEM"
        required: false

jobs:
  yaml-checks:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.container_image }}
    timeout-minutes: 15

    steps:
      - name: Generate GitHub App Token
        id: app-token
        if: inputs.github_app_auth != false
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_pem }}
          repositories: |
            ${{ inputs.github_app_repos }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token || github.token }}

      - name: Install make
        run: |
          apk add --no-cache make

      - name: Check yaml
        run: |
          make ${{ inputs.make_command }}
