name: Cloud Run Cleanup Advanced (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment name"
      knative_yaml:
        required: true
        type: string
        description: "Path to the Knative YAML file for this deployment"
  
jobs:
  cleanup:
    runs-on: zondax-runners
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        region: 
          - ${{ vars.PULUMI_GAR_LOCATION }}
    permissions:
      id-token: write # Enables automatic ID token injection for google-github-actions/auth
      contents: read # Required for actions/checkout and GitHub API access
      pull-requests: write # Required for commenting on PRs
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.PULUMI_DEPLOY_WIF_PROVIDER }}
          service_account: ${{ vars.PULUMI_SA_CLOUDRUN }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
        
      - name: Install yq
        run: |
          go install github.com/mikefarah/yq/v4@latest
        
      - name: Read knative yaml for service name
        id: read-config
        run: |
          if [ -f "${{ inputs.knative_yaml }}" ]; then
            # Copy and process the yaml file to replace placeholders
            cp ${{ inputs.knative_yaml }} service.temp.yaml
            # Replace PR_NUMBER placeholder if present
            sed -i "s#<PR_NUMBER>#${{ github.event.number }}#g" service.temp.yaml
            # Replace <REGION> placeholder if present  
            sed -i "s#<REGION>#${{ matrix.region }}#g" service.temp.yaml
            
            SERVICE_NAME=$(yq '.metadata.name' service.temp.yaml)
            echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          else
            echo "Knative yaml file not found: ${{ inputs.knative_yaml }}"
            exit 1
          fi

      - name: Set final service name
        id: set-service-name
        run: |
          # The service name already includes PR number after placeholder replacement
          FINAL_SERVICE_NAME="${{ steps.read-config.outputs.service_name }}"
          # Always sanitize the service name to ensure it follows Cloud Run naming conventions
          SAFE_SERVICE_NAME=$(echo "$FINAL_SERVICE_NAME" | tr '/' '-' | tr '_' '-' | tr '.' '-' | tr '[:upper:]' '[:lower:]')
          echo "safe_service_name=$SAFE_SERVICE_NAME" >> $GITHUB_OUTPUT

      - name: Delete Cloud Run Service (Final Name)
        run: |
          echo "Deleting Cloud Run service: ${{ steps.set-service-name.outputs.safe_service_name }} in region ${{ matrix.region }}"
          gcloud run services delete ${{ steps.set-service-name.outputs.safe_service_name }} --project ${{ vars.PULUMI_GCP_PROJECT_ID }} --region ${{ matrix.region }} --platform managed --quiet || true