name: Post PR Comment (Reusable)

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: string
        description: "PR number to comment on"
      comment_title:
        required: false
        type: string
        default: "Preview Deployment"
        description: "Title for the comment"
      url:
        required: false
        type: string
        description: "URL to include in the comment"
      url_title:
        required: false
        type: string
        default: "View Preview"
        description: "Title for the URL link"
      additional_message:
        required: false
        type: string
        description: "Additional message to include in the comment"
      comment_body:
        required: false
        type: string
        description: "Full comment body (overrides other fields if provided)"
      comment_identifier:
        required: false
        type: string
        default: "automated-comment"
        description: "Unique identifier to find and update existing comments"

permissions:
  contents: read
  pull-requests: write

jobs:
  post-comment:
    runs-on: zondax-runners
    steps:
      - name: Post or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ inputs.issue_number }}
          comment-id: ${{ inputs.comment_identifier }}
          body: |
            ${{ 
              inputs.comment_body != '' && inputs.comment_body ||
              (inputs.url != '' && format('**🚀 {0}**

            {1}

            🔗 [{2}]({3})', inputs.comment_title, inputs.additional_message != '' && inputs.additional_message || 'Your PR preview has been deployed and is available at:', inputs.url_title, inputs.url)) ||
              format('**{0}**

            {1}', inputs.comment_title, inputs.additional_message)
            }}
