name: Reusable Zup Make

on:
  workflow_call:
    inputs:
      base_branch:
        description: "The branch to create PRs against"
        type: "string"
        required: true
      pr_title:
        description: "PR title"
        type: "string"
        required: true
      pr_label:
        description: "PR label"
        type: "string"
        required: true
      commit_message:
        description: "Commit message"
        type: "string"
        required: true
      pr_body:
        description: "PR body"
        type: "string"
        required: false
        default: "This is an automated PR."
      docker_image:
        description: "Docker image to pull from"
        type: "string"
        default: ""
        required: true
      docker_tag:
        description: "Docker image tag"
        type: "string"
        default: ""
        required: true
      source_dir:
        description: "Source directory in the container"
        type: "string"
        default: ""
        required: true
      target_dir:
        description: "Target directory in the repository"
        type: "string"
        default: ""
        required: true
      github_app_auth:
        description: "Use GitHub App Token"
        required: false
        type: boolean
        default: false
      github_app_repos:
        description: "Additional repositories to access (one per line)"
        required: false
        type: string
        default: ""
    secrets:
      custom_token:
        description: "GitHub token for authentication"
        required: true
      app_id:
        description: "GitHub App ID"
        required: false
      app_pem:
        description: "GitHub App PEM"
        required: false

jobs:
  make-update:
    uses: ./.github/workflows/.zup.yaml
    with:
      base_branch: ${{ inputs.base_branch }}
      pr_title: ${{ inputs.pr_title }}
      pr_label: ${{ inputs.pr_label }}
      commit_message: ${{ inputs.commit_message }}
      pr_body: ${{ inputs.pr_body }}
      github_app_auth: ${{ inputs.github_app_auth }}
      github_app_repos: ${{ inputs.github_app_repos }}
      inline_script: |
        #!/bin/bash
        set -e

        # Update make files from container
        echo "Pulling ${{ inputs.docker_image }}:${{ inputs.docker_tag }}..."
        docker pull ${{ inputs.docker_image }}:${{ inputs.docker_tag }}

        # Extract files from container
        CONTAINER_ID=$(docker create --entrypoint true ${{ inputs.docker_image }}:${{ inputs.docker_tag }})
        rm -rf ${{ inputs.target_dir }} && mkdir -p ${{ inputs.target_dir }}
        docker export "$CONTAINER_ID" | tar x --strip-components=1 -C ${{ inputs.target_dir }} ${{ inputs.source_dir }}
        docker rm "$CONTAINER_ID"

        echo "Successfully updated ${{ inputs.target_dir }}"
    secrets:
      custom_token: ${{ secrets.custom_token }}
