name: Reusable Zup

on:
  workflow_call:
    inputs:
      base_branch:
        description: "The branch to create PRs against"
        type: "string"
        required: true
      pr_title:
        description: "PR title"
        type: "string"
        default: "ZUP - .make update"
        required: false
      pr_label:
        description: "PR label"
        type: "string"
        default: "zup"
        required: false
      commit_message:
        description: "Commit message"
        type: "string"
        required: true
      pr_body:
        description: "PR body"
        type: "string"
        required: false
        default: "This is an automated PR."
      external_script_path:
        description: "Path to the update script relative to repository root"
        type: "string"
        required: false
      inline_script:
        description: "Inline script to execute instead of a file"
        type: "string"
        required: false
    secrets:
      custom_token:
        description: "GitHub token for authentication"
        required: true

jobs:
  zup:
    runs-on: zondax-runners
    container:
      image: ubuntu:24.04
    timeout-minutes: 15
    env:
      PR_TITLE: "🤖 ${{ inputs.pr_title }}"
      PR_LABEL: "zup-${{ inputs.pr_label }}"
      BASE_BRANCH: "${{ inputs.base_branch }}"
      BRANCH_PREFIX: "zup-${{ inputs.pr_label }}"
      COMMIT_MESSAGE: "${{ inputs.commit_message}}"
      PR_BODY: "${{ inputs.pr_body }}"
    steps:
      - name: Install Git
        run: |
          apt-get update && apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.custom_token }}"

      - name: Set up Git
        run: |
          git config --global user.name "Zondax Actions Bot"
          git config --global user.email "actions@zondax.ch"
          git config --global --add safe.directory "$(pwd)"

      - name: Create branch name
        id: branch-name
        run: |
          BRANCH_NAME="${{ env.BRANCH_PREFIX }}-$(date +%Y%m%d)"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Install GitHub CLI
        run: |
          apt-get update
          apt-get install -y gh jq

      - name: Close existing PRs
        if: github.event_name != 'pull_request'
        run: |
          gh auth login --with-token <<< "${{ secrets.custom_token }}"
          # Search for PRs with our specific label
          gh pr list --search "label:${{ env.PR_LABEL }}" --state open --json number,title,headRefName | \
          jq -c '.[]' | \
          while read -r pr; do
            PR_NUMBER=$(echo $pr | jq -r '.number')
            BRANCH_NAME=$(echo $pr | jq -r '.headRefName')
            echo "Closing PR #$PR_NUMBER and deleting branch $BRANCH_NAME"
            gh pr close $PR_NUMBER --comment "Closing in favor of a new automated PR from the zup workflow"
            gh api repos/{owner}/{repo}/git/refs/heads/$BRANCH_NAME -X DELETE || echo "Could not delete branch $BRANCH_NAME"
          done
        env:
          GH_TOKEN: "${{ secrets.custom_token }}"

      - name: Execute update script
        shell: bash
        run: |
          # Validate that only one script source is provided
          if [ ! -z "${{ inputs.inline_script }}" ] && [ ! -z "${{ inputs.external_script_path }}" ]; then
            echo "::error::Cannot specify both inline_script and external_script_path. Please choose one method."
            exit 1
          fi

          # Check if we have an inline script or a script path
          if [ ! -z "${{ inputs.inline_script }}" ]; then
            echo "Executing inline script"
            echo "${{ inputs.inline_script }}" > /tmp/inline_script.sh
            chmod +x /tmp/inline_script.sh
            if ! bash /tmp/inline_script.sh; then
              echo "::error::Inline script failed to execute"
              exit 1
            fi
          else
            # Validate script path
            SCRIPT_PATH="${{ inputs.external_script_path }}"
            if [ -z "$SCRIPT_PATH" ]; then
              echo "::error::No update script path or inline script provided"
              exit 1
            fi

            if [ ! -f "$SCRIPT_PATH" ]; then
              echo "::error::Update script not found at: $SCRIPT_PATH"
              exit 1
            fi

            # Make script executable
            chmod +x "$SCRIPT_PATH"

            # Execute the script with proper error handling
            echo "Executing update script: $SCRIPT_PATH"
            if ! bash "$SCRIPT_PATH"; then
              echo "::error::Update script failed to execute"
              exit 1
            fi
          fi
          echo "Script executed successfully"

      - name: Check for changes
        id: git-check
        run: |
          git add -A  # This is recursive, adds all changes in the repository
          if git diff --staged --quiet; then
            echo "No changes detected in the repository"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in the repository"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: "${{ secrets.custom_token }}"
          commit-message: "${{ env.COMMIT_MESSAGE }}"
          title: "${{ env.PR_TITLE }}"
          body: "${{ env.PR_BODY }}"
          branch: ${{ steps.branch-name.outputs.branch_name }}
          base: ${{ env.BASE_BRANCH }}
          delete-branch: true
          labels: ${{ env.PR_LABEL }}
